apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: rest-endpoint
  type: NodePort
  selector:
    app: rest-api